### ISSUE TITLE
Create a bare project

### ISSUE THREAD

**Issue by Forcasius** [UnfinishedGames/project_dark#1]
Create a bare unity project, that can be pulled from every developer.
It must be:
- shareable (pull it, open it with unity, work)
- contain everything, so all devs can start working independently
- able to build from Windows and Linux
- runnable from Windows and Linux

**Comment by Forcasius** [comment]
Project files added. Need to confirm that a different OS/developer can work with it.

**Comment by GitInMaRepo** [comment]
Can build and run project after checkout on Windows 10 machine.
