### ISSUE TITLE
Health state for the players

### ISSUE THREAD

**Issue by Forcasius** [UnfinishedGames/project_dark#10]
We want violence! Lets introduce health and damage for the players and let the floor be crimson with pixel blood!

**Comment by GitInMaRepo** [comment]
I'm on it

**Comment by GitInMaRepo** [comment]
Done, please check

**Comment by GitInMaRepo** [comment]
Fixed known NullRefExceptions

**Comment by Forcasius** [comment]
I works. When the player is hit, the cake gets reduced. If the cake is gone, the games gets reset and the win counter of the opponent gets increased - AWESOME!

(F.Y.I.: I have fixed another NullPointerException)
