### ISSUE TITLE
Enhance the gamepad controlls

### ISSUE THREAD

**Issue by Forcasius** [UnfinishedGames/project_dark#12]
The controls fell a bit rough right now.
The input should be smoother - also find out how to find settings for different game pads.

**Comment by Forcasius** [comment]
The controls for the movement are analog now (push the stick further to move faster). The looking controls are smoother now (I've played with the "Deathzone", "Sensitivity", "Gravity" controls).

Please check if it also works with a different setup.

**Comment by GitInMaRepo** [comment]
My controller is crap, Can't test
