### ISSUE TITLE
Movement script - keyboard

### ISSUE THREAD

**Issue by Forcasius** [UnfinishedGames/project_dark#4]
Create a script that can control the players via the keyboard.
Only basic movement is enough (move up/down/left/right) for now.

Make it turn if you want.

**Comment by GitInMaRepo** [comment]
Mouse Movement is complete.
Test please.

**Comment by Forcasius** [comment]
When the mouse leaves the gaming-area, the movement is not tracked anymore - this might lead to unintuitive behaviour.
But other than that: it works :)
