### ISSUE TITLE
Introduce a crosshair

### ISSUE THREAD

**Issue by Forcasius** [UnfinishedGames/project_dark#7]
We want a crosshair, so we always know where we are facing.
For the mouse controls it could only replace the mouse pointer.
For the gamepad, it should be located on a fixed circle around the player.

**Comment by GitInMaRepo** [comment]
Done. Please test

**Comment by Forcasius** [comment]
Well, it works just fine - but from a "game design point of view" it is quite unfortunate, that the crosshair is giving away our position. We might have to rethink that.
