### ISSUE TITLE
Create "TapTap" 'sound'

### ISSUE THREAD

**Issue by Forcasius** [UnfinishedGames/project_dark#8]
When the player moves, an UI-Element should be shown that visualizes the the sound he makes.
Like in a comic.

Some ideas:
- The "Tap"s could be placed in random size and random position around the player.
- The "Tap"s could always start at the player feet and grow in size
- There could be a small "Tap" and a big "Tap" shown at the same time at the player position.
- ...

In all cases: It should follow the player as he moves.

**Comment by GitInMaRepo** [comment]
"Tap" and "Vroom" added. Test please

**Comment by Forcasius** [comment]
Works like a charm!
